### PR TITLE
Remove seabug-specific metadata code

### PR DESCRIPTION
**Pull request by rynoV**
This code is being transferred over to its own repo in [this PR](https://github.com/mlabs-haskell/seabug-contracts/pull/7). CC @samuelWilliams99 

### Pre-review checklist

- [N/A] All code has been formatted using our config (`make format` for Purescript, `nixpkgs-fmt` for Nix)
- [N/A] All Purescript imports are explicit, including constructors
- [N/A] **All** existing examples have been run locally against a fully-synced testnet node
- [x] The integration and unit tests have been run (`npm run test`) locally
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`)
  - Pretty sure this isn't applicable? I assume it was only seabug using that code, but I can update the changelog if you want

### CODE REVIEW

**Review by ngua — CHANGES_REQUESTED** [review]
Thanks for taking care of this!

Please update the changelog under `## Unreleased` (using the `### Removed` subheading)

**Review by vvtran — COMMENTED** [review]
lgtm, just address what @ngua said.

**Comment by klntsky** [comment]
The repo is 404 for me.

**Comment by samuelWilliams99** [comment]
Its a private repo, and perms are being switched around a bit at the moment, the exact destination of this code isn't as important

**Review by klntsky — APPROVED** [review]

**Pull request merged**
