### PR TITLE
Hashing (was #243)

### PR DESCRIPTION
**Pull request by ngua**
Replay of #243 from @MangoIV

### CODE REVIEW

**Comment by MangoIV** [comment]
Thank you! I see you already resolved the missing issues yourself, sorry for not being quick enough.

**Comment by MangoIV** [comment]
I already integrated the changes from #419 but I don't have permission to push to this branch. (just wanted to leave a note here so that work doesn't need to be duplicated)

**Comment by ngua** [comment]
I'm going to close this since it seems to be part of #419

**Comment by MangoIV** [comment]
I mean we could've integrated it to decrease  the amount of stuff  to review in #419 but your call :)

**Pull request closed without merging**
