### PR TITLE
Switch to preview

### LINKED ISSUE #1030: Switch to preview
We want PlutusV2 features in examples and tests sooner than the hardfork of `preprod`

### PR DESCRIPTION
**Pull request by klntsky**
Closes #1030

### Pre-review checklist

- [x] All code has been formatted using our config (`make format`)
- [x] Any new API features or modification of existing behavior is covered as defined in our [test plan](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md)
- [x] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

### CODE REVIEW

**Comment by klntsky** [comment]
```
$ psql --host localhost --port 5432 -U ctxlib -d ctxlib
password: ctxlib

update last_block set slot=142437, hash='b69536b82f5ce270246a80188f29311145a92093072b75f89a41ee20859cc608';
```

**Review by jy14898 — APPROVED** [review]

**Review by errfrom — APPROVED** [review]
Just tested a PlutusV2 contract against `preview` testnet, and everything works as expected

**Comment by klntsky** [comment]
We need to first merge lode though.

**Comment by klntsky** [comment]
Closing in favor of #1034

**Pull request closed without merging**
