### PR TITLE
Add {Encode,Decode}Aeson instances for TransactionUnspentOutput

### PR DESCRIPTION
**Pull request by aske**
Closes # .

### Pre-review checklist

- [x] All code has been formatted using our config (`make format`)
- [ ] Any new API features or modification of existing behavior is covered as defined in our [test plan](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md)
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

### CODE REVIEW

**Review by rmgaray — COMMENTED** [review]
This looks pretty much the same as what I wrote. Do you mind if I add the necessary changes for `TransactionInput` as well?

**Comment by aske** [comment]
>This looks pretty much the same as what I wrote. Do you mind if I add the necessary changes for TransactionInput as well?

Were there extra changes required? This PR should cover `Encode/DecodeAeson` for `TransactionInput` via `derive newtype`.

**Comment by aske** [comment]
Yeah, adding tests would be great

**Comment by rmgaray** [comment]
My apologies for not adding tests to this PR, I've been quite busy this week. Would you mind if I add another Aeson instances that I need (more specifically, an instance for `PaymentPubKeyHash`)?

**Comment by aske** [comment]
Sounds good

**Comment by rmgaray** [comment]
@aske Just added some unit tests and updated changelog, I think this PR is ready for review.

**Review by klntsky — APPROVED** [review]

**Comment by klntsky** [comment]
We will recreate this PR from a local branch

**Comment by klntsky** [comment]
Closing in favor of #1222

**Pull request closed without merging**
