### PR TITLE
update cardano-node to 1.35.2

### LINKED ISSUE #714: firstBlock config seems to be ignored
When runing `nix run .#ctl-runtime` in `407fde2f522feac4b9c86a8579b6b3cb0cdfb70f` (currently the newest commit on develop) the ogmious datum cache starts at slot 0 rather than the slot specified in firstBlock.

### PR DESCRIPTION
**Pull request by Geometer1729**
Closes #714.

### Pre-review checklist

- [x] All code has been formatted using our config (`make format` for Purescript, `nixpkgs-fmt` for Nix)
- [x] All Purescript imports are explicit, including constructors
- [ ] **All** existing examples have been run locally against a fully-synced testnet node
- [x] The integration and unit tests have been run (`npm run test`) locally
- [x] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`)

### CODE REVIEW

**Review by klntsky — APPROVED** [review]

**Comment by Geometer1729** [comment]
I can't get the example to work, it doesn't seem to work on develop either.

**Comment by klntsky** [comment]
@Geometer1729 could you please check if it worked before the change? If it does not, it's not a blocker. Thank you for being careful with this!

**Comment by Geometer1729** [comment]
> @Geometer1729 could you please check if it worked before the change? If it does not, it's not a blocker. Thank you for being careful with this!
It did not work before the change.

**Comment by Geometer1729** [comment]
I'm having similar issues with other stuff that I know worked last week. It seems like maybe testnet is just having issues today?

**Review by ngua — APPROVED** [review]

**Pull request merged**
