### PR TITLE
Combine examples into a single module

### PR DESCRIPTION
**Pull request by ngua**
We should be running all examples locally when opening PRs (at the very least until #465 is addressed). As it is, it's inconvenient to edit the Makefile or issue all of the commands manually. This adds an `Examples.Combined` module for convenience

### CODE REVIEW

**Comment by ngua** [comment]
Let's add this after #456 is merged, it might simplify things

**Comment by firefrorefiddle** [comment]
Alternatively, we could configure the Webpack server so that each example has it's own URL?

**Comment by ngua** [comment]
@firefrorefiddle If you're willing to deal with webpack I'd be OK with that :)

**Comment by ngua** [comment]
This has been superseded by the approach used in #649

**Pull request closed without merging**
