### PR TITLE
Bump Ogmios

### LINKED ISSUE #639: Upgrade to Ogmios v5.5
There's an official release now

### PR DESCRIPTION
**Pull request by ngua**
Closes #639

### CODE REVIEW

**Review by vvtran — APPROVED** [review]
Out of curiosity, what's the reason for removing the Dockerfile in this rev?

**Comment by vvtran** [comment]
Hang on, sorry, I shouldn't have approved. Getting this on `npm run test`
```
viet@viet-ThinkPad-E15-Gen-2:~/Work/MLabs/cardano-browser-tx$ npm run test

> cardano-transaction-lib@1.0.1 test /home/viet/Work/MLabs/cardano-browser-tx
> npm run unit-test && npm run integration-test


> cardano-transaction-lib@1.0.1 unit-test /home/viet/Work/MLabs/cardano-browser-tx
> spago run --main Test.Unit

           Src   Lib   All
Warnings   0     0     0  
Errors     0     0     0  
[info] Build succeeded.
/home/viet/Work/MLabs/cardano-browser-tx/output/Types.BigNum/foreign.js:14
exports.one = lib.BigNum.one();
                         ^

TypeError: lib.BigNum.one is not a function
    at Object.<anonymous> (/home/viet/Work/MLabs/cardano-browser-tx/output/Types.BigNum/foreign.js:14:26)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/viet/Work/MLabs/cardano-browser-tx/output/Types.BigNum/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[error] Running failed; exit code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cardano-transaction-lib@1.0.1 unit-test: `spago run --main Test.Unit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cardano-transaction-lib@1.0.1 unit-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/viet/.npm/_logs/2022-07-01T08_44_25_979Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cardano-transaction-lib@1.0.1 test: `npm run unit-test && npm run integration-test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cardano-transaction-lib@1.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/viet/.npm/_logs/2022-07-01T08_44_26_000Z-debug.log
```
Someone mentioned this on discord actually. This shouldn't be a sync issue should it?

I didn't have this issue when we upgraded https://github.com/Plutonomicon/cardano-transaction-lib/pull/609

**Comment by ngua** [comment]
@vvtran This doesn't seem to have anything to do with Ogmios. Have you re-run `nix develop`?

**Comment by ngua** [comment]
@klntsky The dockerfile was really out of date and I didn't have time to fix it yet. Rather than deal with the upgrade I just removed it. The one from upstream won't work either

**Comment by ngua** [comment]
I'm just going to merge this for now since @vvtran's problem seems to be unrelated

**Comment by vvtran** [comment]
I did try rerunning nix develop a few times but didn't work. Now it's fine though, weird.

**Pull request merged**
