### PR TITLE
Add Conway and enable sanchonet

### LINKED ISSUE #1543: Use new interface for era and time interval
This is a follow-up to #1517, which defines a new interface for era and time intervals. We need to do two more things:

* Replace any use of the old interface with the new; and
* Remove and/or deprecate the old interface

### LINKED ISSUE #1564: eraSummaries decoding error
I use last commit #1532 from develop branch.  And I am getting error in eraSummaries:

```bash
Error: Failed to parse the result: An error occurred while decoding a JSON value:
  At object key 'start':
  At object key 'time':
  Expected value of type 'Number'.
```
I guess it is an issue with new Ogmios 6.0 format. Now `"time":{"seconds":0} ` is an object , not a Number.

I tried it with docker image `cardanosolutions/ogmios:v6.0.0-rc4` , but everything ok with `ctl-runtime-ogmios`

### PR DESCRIPTION
**Pull request by klarkc**
- Add Conway era and enable cardano-transaction-lib on sanchonet
- Bump ogmios to https://github.com/CardanoSolutions/ogmios/commit/395776e7f6cfdbef756aa7abe8030b9cc2e0ba8d
- Fork kupo from v2.8.0
- Bump cardano-node to 8.11.0-pre
- Bump cardano-serialization-lib to 12.0.0-alpha.29
- Add PlutusV3
- Add `AlwaysMintsV3` example
- Add `AlwaysSucceedsV3` example (see https://github.com/Plutonomicon/cardano-transaction-lib/pull/1593#issuecomment-2101350297)
- Replace node2nix with npmlock2nix to allow mlabs CSL fork

Depends on mlabs-haskell/kupo-nixos#13
Depends on mlabs-haskell/ogmios-nixos#2
Depends on mlabs-haskell/cardano-serialization-lib-gc#1
Depends on CardanoSolutions/ogmios#363
Depends on CardanoSolutions/ogmios#386

Fix #1564 
Closes #1543 

### Pre-review checklist

- [x] In sync with latest Sanchonet node
- [x] All code has been formatted using our config (`make format`)
- [x] Any API modification of existing behavior are covered with tests
- [ ] Any new API features of existing behavior are covered with tests
- [ ] Re-enable Plutip
- [ ] Re-enable skipped tests
- [ ] `AdditionalUtxos` example working
- [x] `AlwaysMints` example working
- [ ] `AlwaysSucceeds` example working
- [ ] `AlwaysSucceedsV2` example working
- [ ] `ApplyArgs` example working
- [ ] `ChangeGeneration1-1` example working
- [ ] `ChangeGeneration1-3` example working
- [ ] `ChangeGeneration3-1` example working
- [x] `Cip30` example working
- [x] `Datums` example working
- [x] `DropTokens` example working
- [x] `ECDSA` example working
- [x] `MintsMultipleTokens` example working
- [x] `NativeScriptMints` example working
- [x] `OneShotMinting` example working
- [x] `OneShotMintingV2` example working
- [ ] `PaysWithDatum` example working
- [x] `P2h2Pkh` example working
- [x] `ReferenceInputs` example working
- [ ] `ReferenceInputsAndScript` example working
- [x] `Schnorr` example working
- [x] `SendsToken` example working
- [x] `SignData` example working
- [x] `SignMultiple` example working
- [ ] `TxChaining` example working
- [ ] `Utxos` example working
- [x] `Wallet` example working
- [ ] The template (`templates/ctl-scaffold`) has been [updated](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/development.md#maintaining-the-template)
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Changed`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

### CODE REVIEW

**Comment by klntsky** [comment]
Hi! Sorry for not being able to review it sooner, I'll hopefully have free time next week

**Comment by klarkc** [comment]
A breaking change on Sanchonet is causing a bug in Kupo: https://github.com/CardanoSolutions/kupo/issues/164, this is blocking us from querying the blockchain utxos.

**Comment by klarkc** [comment]
@klntsky I could keep going with [cardano-dev-wallet](https://github.com/mlabs-haskell/cardano-dev-wallet) and a local testnet with [sanchonet-demo](https://github.com/input-output-hk/sanchonet-demo), does CTL supports this dev-wallet?

**Comment by klntsky** [comment]
@klarkc no one tested cardano-dev-wallet with sancho, what are the CSL version requirements for sancho? That, and ogmios/kupo version are limiting factors

**Comment by klarkc** [comment]
@klntsky, I see. CSL for Sancho is being developed in Emurgo/cardano-serialization-lib#636, which is being used for this PR. At the moment, we are continuing to fix the breaking changes on Kupo with the goal of reaching the Sancho tip. Therefore, there is no need for the dev wallet now.

**Comment by klarkc** [comment]
Tried to evaluate a PlutusV3 transaction, but ogmios failed, log:

```
AlonzoTx {body = TxBodyConstr BabbageTxBodyRaw {btbrSpendInputs = fromList [TxIn (TxId {unTxId = SafeHash "9bc2008babae1a0750d926f12d53e5ee77f042853cea711dded5fc5885121e0a"}) (TxIx 4)], btbrCollateralInputs = fromList [], btbrReferenceInputs = fromList [], btbrOutputs = StrictSeq {fromStrict = fromList [Sized {sizedValue = (Addr Testnet (ScriptHashObj (ScriptHash "6ea06f17c77d52f08e208ded10b0b7cffec0185efb4220a1ac18aa3f")) (StakeRefBase (KeyHashObj (KeyHash "899caf87c60e581582a408206fe6cc58e7a779afbc516b3726a82f2e"))),MaryValue (Coin 2000000) (MultiAsset (fromList [])),DatumHash (SafeHash "923918e403bf43c34b4ef6b48eb2ee04babed17320d8d1b9ff9ad086e86f44ec"),SNothing), sizedSize = 99},Sized {sizedValue = (Addr Testnet (KeyHashObj (KeyHash "a838a4e1280f3bf8e1462f7a9d728b3e277427cd08d0512594603ccd")) (StakeRefBase (KeyHashObj (KeyHash "899caf87c60e581582a408206fe6cc58e7a779afbc516b3726a82f2e"))),MaryValue (Coin 12496750000) (MultiAsset (fromList [])),NoDatum,SNothing), sizedSize = 69}]}, btbrCollateralReturn = SNothing, btbrTotalCollateral = SNothing, btbrCerts = StrictSeq {fromStrict = fromList []}, btbrWithdrawals = Withdrawals {unWithdrawals = fromList []}, btbrTxFee = Coin 0, btbrValidityInterval = ValidityInterval {invalidBefore = SNothing, invalidHereafter = SNothing}, btbrUpdate = SNothing, btbrReqSignerHashes = fromList [], btbrMint = MultiAsset (fromList []), btbrScriptIntegrityHash = SNothing, btbrAuxDataHash = SNothing, btbrTxNetworkId = SJust Testnet} (blake2b_256: SafeHash "434096cd744da6906aa3813cf2aa3ba171bde2fd5f9d231d3a48828d07c5ee2c"), wits = AlonzoTxWitsRaw {atwrAddrTxWits = fromList [], atwrBootAddrTxWits = fromList [], atwrScriptTxWits = fromList [], atwrDatsTxWits = TxDatsConstr TxDatsRaw {unTxDatsRaw = fromList [(SafeHash "923918e403bf43c34b4ef6b48eb2ee04babed17320d8d1b9ff9ad086e86f44ec",DataConstr Constr 0 [] (blake2b_256: SafeHash "923918e403bf43c34b4ef6b48eb2ee04babed17320d8d1b9ff9ad086e86f44ec"))]} (blake2b_256: SafeHash "d89d18b7b8eb394cd1ce8ce06e930cf688c5c669a6410ec89dc01c2372043936"), atwrRdmrsTxWits = RedeemersConstr fromList [] (blake2b_256: SafeHash "45b0cfc220ceec5b7c1c62c4d4193d38e4eba48e8815729ce75f9c0ab0e4c1c0")} (blake2b_256: SafeHash "dbbc4ce17958e0431ba7924691ff15f5da2a3b36713e142a2f11b69915ed589b"), isValid = IsValid True, auxiliaryData = SNothing}
DecoderErrorDeserialiseFailure "witness" (DeserialiseFailure 9 "Empty list found, expected non-empty")
```

https://github.com/Emurgo/cardano-serialization-lib/pull/636/commits/0be14e4a71841ab9779372621a91553e729242e9 mentions an empty witness validation on serialization, I'll bump CSL to see if it will show me any additional useful info.

**Comment by klarkc** [comment]
Kupo sync halted, addressing in https://github.com/CardanoSolutions/kupo/pull/168

**Comment by klarkc** [comment]
submitTransaction is failing


<details><summary>Details</summary>
<p>
message: {"jsonrpc":"2.0","method":"submitTransaction","error":{"code":3113,"message":"The transaction failed because the provided script integrity hash doesn't match the computed one. This is crucial for ensuring the integrity of cost models and Plutus version used during script execution. The field 'data.providedScriptIntegrity' correspond to what was given, if any, and 'data.computedScriptIntegrity' is what was expected. If the latter is null, this means you shouldn't have included a script integrity hash to begin with.","data":{"providedScriptIntegrity":"15dd0a3ac1244430aacc7e95c2734b51f1a8cf2aaf05e5d6e8124cb78ab54cc9","computedScriptIntegrity":"5675d0b3607627653b48941ade5477ac756c58188547e7753be8b38243fb9fe4"}},"id":"submitTransaction-lvy8v66e"}
</p>
</details>

**Comment by klarkc** [comment]
>  Error: Could not get utxo

On `TxChaining` example

**Comment by klarkc** [comment]
> Error: Script evaluation failure while trying to estimate ExUnits

On `Utxos` example

**Comment by errfrom** [comment]
Closing as CTL has already been updated to Conway (see PR https://github.com/Plutonomicon/cardano-transaction-lib/pull/1624).
Thanks for your work @klarkc - your PR served as a valuable reference point.

**Pull request closed without merging**
