### PR TITLE
Add path to ServerConfig

### LINKED ISSUE #728: Add path to ServerConfig
Reposting from Discord:

> Can CTL be configured to send the different WS service requests to the same port but different paths,  like does the ServerConfig->host field support a path i.e. proxying the websocket servers like `https://mydapp.com/api/ogmios/...`, 
`https://mydapp.com/api/odc/...`

### PR DESCRIPTION
**Pull request by weskinner**
Closes #728.

### Pre-review checklist

- [X] All code has been formatted using our config (`make format` for Purescript, `nixpkgs-fmt` for Nix)
- [X] All Purescript imports are explicit, including constructors
- [ ] **All** existing examples have been run locally against a fully-synced testnet node
- [ ] The integration and unit tests have been run (`npm run test`) locally
- [x] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`)

### CODE REVIEW

**Review by ngua — COMMENTED** [review]
Thanks for taking care of this!

Could you add some notes to the documentation please?
- This should go in the changelog, under `## Unreleased` and `### Changed`
- In `doc/getting-started.md`, there's a brief overview of the `ContractConfig` with some examples. This should be documented there

If #731 is merged before this, you might need to change the documentation in a different place

**Comment by weskinner** [comment]
I've updated the changelog @ngua

**Comment by weskinner** [comment]
... and documented

**Comment by ngua** [comment]
Great, thanks @weskinner. This looks good to me, but CI won't run so we can't actually merge it yet. I'll close this PR, open another one from the main repo, and then it can be merged

**Review by ngua — APPROVED** [review]

**Comment by klntsky** [comment]
Thank you @weskinner ! I opened another PR for CI to run: https://github.com/Plutonomicon/cardano-transaction-lib/pull/771

**Pull request closed without merging**
