### PR TITLE
Add faq.md

### PR DESCRIPTION
**Pull request by klntsky**

### CODE REVIEW

**Review by ngua — COMMENTED** [review]
I might suggest changing the document name/title to `faq.md`

**Comment by klntsky** [comment]
OK sounds less frigtening

**Comment by firefrorefiddle** [comment]
> I might suggest changing the document name/title to `faq.md`

Then the contents should be rephrased as questions.

**Review by jy14898 — APPROVED** [review]
Approving as the comments have been addressed

**Pull request merged**
