### PR TITLE
Update ogmios-datum-cache (to the version with darwin build)

### PR DESCRIPTION
**Pull request by aske**
### Pre-review checklist

- [ ] All code has been formatted using our config (`make format` for Purescript, `nixpkgs-fmt` for Nix)
- [ ] All Purescript imports are explicit, including constructors
- [ ] **All** existing examples have been run locally against a fully-synced testnet node
- [ ] The integration and unit tests have been run (`npm run test`) locally
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`)

### CODE REVIEW

**Comment by klntsky** [comment]
This is a bugfix, right? Please add a changelog entry if so.

**Comment by aske** [comment]
@klntsky added an entry.

**Review by klntsky — APPROVED** [review]
Cool, thank you!

Is this the only thing that was blocking us on darwin?

**Comment by klntsky** [comment]
I will re-create this PR from a branch in this repo (CI only runs on our branches).

**Comment by klntsky** [comment]
Closing in favor of https://github.com/Plutonomicon/cardano-transaction-lib/pull/773

**Pull request closed without merging**
