### PR TITLE
Wait until the button is visible before clicking on it

### PR DESCRIPTION
**Pull request by leomayleomay**
### Pre-review checklist

- [ ] All code has been formatted using our config (`make format`)
- [ ] Any new API features or modification of existing behavior is covered as defined in our [test plan](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md)
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

### CODE REVIEW

**Comment by klntsky** [comment]
I'm in the process of a massive E2E rewrite. See `klntsky/rewrite-e2e` branch. There's a change that follows the same logic there.

I'm going to close this PR when we merge the other implementation, but thank you anyway!

**Comment by leomayleomay** [comment]
@klntsky thank you for letting me know :)

**Comment by leomayleomay** [comment]
@klntsky I am wondering if Nami wallet is working as expected in the branch you are currently working on?

**Comment by klntsky** [comment]
@leomayleomay It hasn't been tried there.

The PR in question: https://github.com/Plutonomicon/cardano-transaction-lib/pull/1075

**Pull request closed without merging**
