### PR TITLE
buildCtlRuntime: better config management

### PR DESCRIPTION
**Pull request by Synthetica9**
Previously, it was not possible to override only part of a config item (for example, only setting the port for postgres). This PR fixes that, and as a bonus, also allows you to refer to the final value of config items.

A few examples to clear this up:

```
# Correctly changes the dbConnectionString
buildCtlRuntime ({ postgres.port = 9001; postgres.user = "asdf"; })
# Refer back to the final config:
buildCtlRuntime (final: { node.port = postgres.port + 1; })
```

### CODE REVIEW

**Review by ngua — COMMENTED** [review]
LGTM, thanks! Could you also update the example in the readme that shows how to use `buildCtlRuntime` please?

**Review by klntsky — APPROVED** [review]

**Comment by Synthetica9** [comment]
Like this, or do you want more doc?

**Comment by klntsky** [comment]
@Synthetica9 Would be cool if both ways to call `buildCtlRuntime` were mentioned (with attrset and with function as argument).

**Comment by ngua** [comment]
I'm going to close this and re-open it from a branch on the main repo

**Pull request closed without merging**
