### PR TITLE
Do not propagate "listener cancelled" error to Aff

### LINKED ISSUE #827: Lower level from ERROR to TRACE for dispatcher reports on missing listeners
These should be TRACE:

```
[ERROR] 2022-07-29T12:23:12.937Z unexpected error on input: {"reflection":"GetDatumByHash-1gy1h88mj6l66fqztp","methodname":"GetDatumByHash","result":{"DatumFound":{"value":3}},"version":"1.0","servicename":"ogmios-datum-cache","type":"jsonwsp/response"} Error:(JsError (message "Request Id GetDatumByHash-1gy1h88mj6l66fqztp has been cancelled"))
```

### PR DESCRIPTION
**Pull request by klntsky**
Closes #827

Also prevents duplicate logging by removing logger from `_onWsError` argument - the handler should decide, what to do with the error message, we should not tie WS code to our logging machinery.

### Pre-review checklist

- [x] All code has been formatted using our config (`make format` for Purescript, `nixpkgs-fmt` for Nix)
- [x] All Purescript imports are explicit, including constructors
- [x] The integration and unit tests have been run (`npm run test`) locally
- [x] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

### CODE REVIEW

**Review by ngua — APPROVED** [review]

**Comment by ngua** [comment]
This is interesting @klntsky -- it looks like `Examples.MintsMultipleTokens` is flaky too? I just re-ran the exact failing Plutip test (`nix build -L 'github:Plutonomicon/cardano-transaction-lib?rev=1f5494ae02690bb147f326a7c53913b6b265854b#hydraJobs.x86_64-linux.ctl-plutip-test'`) and the failing example passed

**Comment by klntsky** [comment]
@ngua 
>   (ClientHttpError There was a problem making the request: request failed)

Not related to this particular test.

This must be because we detect `ctl-server` startup incorrectly. The line we wait for (`"Successfully connected to Ogmios"`) can be printed before the webserver has fully started. This is extremely rare, because only server initialization code is executing after the line is printed, but since CI machine is less capable than any dev PC this hasn't been catched yet.

**Comment by ngua** [comment]
Apparently the empty commit didn't actually trigger CI

**Comment by ngua** [comment]
CI at last!

**Pull request merged**
